version: "3"

services:
  phx_web:
    build: .
    container_name: phx_web
    ports:
      - "4000:4000"
    command: mix phx.server
    env_file: 
      - .env
    volumes:
      - .:/app

  phx_db:
    image: postgres:13.3
    container_name: phx_db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=phx
      - POSTGRES_PASSWORD=postgres
